language: java
jdk: openjdk8
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
script: mvn clean package
install: mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  - provider: releases
    api_key:
      secure: MOJaO/9kIjpd0ACh8UH8s6YUYghcPn7wwiXUAHvEXPAL35gJrXjoAdGoeA0BS9aolZOYvp0Gdto5fsIDtuNccsrd+3wz0LYB55zSfAcXJ6lMrVxj91f2XwPzLrmLd8cHgsgf9JcnYLuLA1HNxwW9aYfg3lLmVAuA34GbbTHcrngT9ERg+Gq9vKatKIJmj5UhTrzsajauTu+Uhs3yt/2qNeQKE784aq4k6hdliCcqPO1q42eyl8pNBgpHUcYcebbPTMCYwl//+R+bLmbpoB3Ig97npXNww3AZIvFGe9792q7fsaLXdM02LXf9cRbRqZR0mO/CtRiYfAuLu72guQBASkLcxPBm+6XgBbzuoxJ/qSMQobEBisgyCAAnErRWyzak74VxzL3tyNtELuEHWPxdmL4kR4pdtbOTXAu8XV3Vti5cPys1d+i2TGN4pIBx9AB4zG66wYFmbxgQsFqTPOnaZuLCgsDXf3ckISt0kvMqMxLPSTxaa8YRN6cCJkAq9Vj3wM0sivJzxZmLTaCAmBAIMCnC2NnKx3ckOqA+OS1+Xw8XJoqjiUj7XAc+OFKisTwxANmon5/k21SXhFiMaIFja5sEVA18YeLs73u/PdQ1mKrYzpAsQarGVERwhcXWkbA5JLviQdlu5ef60mXKimnpakKQ6qXlabP15zo1KfHrpxY=
    file: 
    - client/target/boku-http-auth-client-$project_version-javadoc.jar
    - client/target/boku-http-auth-client-$project_version-sources.jar
    - client/target/boku-http-auth-client-$project_version.jar
    - core/target/boku-http-auth-core-$project_version-javadoc.jar
    - core/target/boku-http-auth-core-$project_version-sources.jar
    - core/target/boku-http-auth-core-$project_version.jar
    - server/target/boku-http-auth-server-$project_version-javadoc.jar
    - server/target/boku-http-auth-server-$project_version-sources.jar
    - server/target/boku-http-auth-server-$project_version.jar
    - tools-zip/target/boku-auth-tools-$project_version.zip 
    skip_cleanup: 'true'
    on:
      repo: boku-inc/boku-http-auth
      branch: master
      tags: true
    name: v$project_version
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      repo: boku-inc/boku-http-auth
      branch: master
      tags: true
